USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE GLUE_DB;
USE SCHEMA GLUE_DB.PUBLIC;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::515424600331:role/dbt-glue-snowpipe-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://dbt-glue-project-bucket-calvinfr1/data/');

DESC INTEGRATION S3_INT; -- Use the STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_ENTERNAL_ID properties to update the trust policy of the IAM role.

CREATE OR REPLACE STAGE GLUE_DB.PUBLIC.S3_STAGE
    STORAGE_INTEGRATION = S3_INT
    URL= 's3://dbt-glue-project-bucket-calvinfr1/data/';
  
ls @GLUE_DB.PUBLIC.S3_STAGE; -- Tests storage integration.

CREATE OR REPLACE TABLE GLUE_DB.PUBLIC.COUNTRY_DETAILS_CP
(
    DATA VARIANT -- Semi-structured JSON data from API Gateway
);

CREATE OR REPLACE PIPE GLUE_DB.PUBLIC.MYPIPE AUTO_INGEST = TRUE AS
    COPY INTO GLUE_DB.PUBLIC.COUNTRY_DETAILS_CP
    FROM @GLUE_DB.PUBLIC.S3_STAGE
    FILE_FORMAT = (TYPE = 'JSON');

SHOW PIPES; -- Use the notification_channel property to create an S3 event notification.

SELECT * FROM GLUE_DB.PUBLIC.COUNTRY_DETAILS_CP;

