USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE SCD2_DB;
USE SCHEMA SCD2_DB.PUBLIC;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::515424600331:role/snowflake-scd2-project-snowpipe-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://snowflake-scd2-project-bucket-calvinfr1/data/');

DESC INTEGRATION S3_INT; -- Use the STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_ENTERNAL_ID properties to update the trust policy of the IAM role.

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = true;

CREATE OR REPLACE STAGE SCD2_DB.PUBLIC.S3_STAGE
  STORAGE_INTEGRATION = S3_INT
  URL = 's3://snowflake-scd2-project-bucket-calvinfr1/data/'
  FILE_FORMAT = MY_CSV_FORMAT;
  
ls @SCD2_DB.PUBLIC.S3_STAGE; -- Tests storage integration.

CREATE OR REPLACE TABLE SCD2_DB.BRONZE.WORK_PRODUCT_COPY
(
    PRODUCT_ID VARCHAR(255) NOT NULL COLLATE 'en-ci'
    ,PRODUCT_NAME VARCHAR(255) NOT NULL COLLATE 'en-ci'
    ,CATEGORY VARCHAR(255) COLLATE 'en-ci'
    ,SELLING_PRICE VARCHAR(50) COLLATE 'en-ci'
    ,MODEL_NUMBER VARCHAR(50) COLLATE 'en-ci'
    ,ABOUT_PRODUCT VARCHAR(5000) COLLATE 'en-ci'
    ,PRODUCT_SPECIFICATION VARCHAR(5000) COLLATE 'en-ci'
    ,TECHNICAL_DETAILS VARCHAR(50000) COLLATE 'en-ci'
    ,SHIPPING_WEIGHT VARCHAR(30) COLLATE 'en-ci'
    ,PRODUCT_DIMENSIONS VARCHAR(100) COLLATE 'en-ci'
    ,INSERT_DTS TIMESTAMP_NTZ(6) NOT NULL
    ,UPDATE_DTS TIMESTAMP_NTZ(6) NOT NULL
    ,SOURCE_FILE_NAME VARCHAR(255) NOT NULL
    ,SOURCE_FILE_ROW_NUMBER VARCHAR(255) NOT NULL
);